{
    'name': 'School',
    'summary': 'School Model manage student, classes, subjects, teacher',
    'description' : 'This is use for testing purpose',
    'author' : 'Tushar_Malhotra',
    'license' : 'AGPL-3',
    'website' : 'https://www.ksolves.com',
    'category' : 'School_Data',
    'version' : '11.0.1.1.0',
    'depends' : ['base', 'hr'],
    'data' : ['views/school_view.xml',
              'views/subject_view.xml',
              'views/class_view.xml',
              'views/student_view.xml',
              'views/teacher_view.xml',
              'views/exam_view.xml',
              'views/exam_wizard_view.xml'],
    # 'demo' : ['demo.xml'],
}

